version: '3.7'

services:
  app:
    build:
         context: .
         dockerfile: ./app/Dockerfile
    command: >
      sh -c "python3 manage.py migrate &&
              python3 manage.py wait_for_db &&
              python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/app
      - ./static:/opt/app/static/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./env/django.env
      - ./env/database.env
      - ./env/whatsapp.env

  db:
    image: postgres:9.5.20-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - ./env/database.env
  
  redis:
    image: redis:alpine
  
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: >
      sh -c "celery -A main worker -l info -B"
    volumes:
      - ./app:/app
    env_file:
      - ./env/django.env
      - ./env/whatsapp.env
      - ./env/database.env
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres_data:
