# Generated by Django 3.2.6 on 2022-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='to',
            field=models.CharField(max_length=1500, verbose_name='Recipient(s) Number'),
        ),
    ]
