# Generated by Django 3.2.6 on 2022-09-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_messages', '0003_auto_20220927_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_body',
            field=models.TextField(max_length=1000, verbose_name='Message Body'),
        ),
    ]
