# Generated by Django 3.2.6 on 2022-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_messages', '0004_alter_whatsappmessage_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Is Canceled?'),
        ),
    ]
