# Generated by Django 3.2.6 on 2022-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpp_messages', '0005_whatsappmessage_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='send_now',
            field=models.BooleanField(default=True, verbose_name='Send Now?'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='date_to_send',
            field=models.DateTimeField(null=True, verbose_name='Date to Send'),
        ),
    ]
